version: "3.9"

services:
  nodered:
    image: 'nodered/node-red:latest'
    pull_policy: always
    container_name: mynodered
    tty: true 
    stdin_open: true
    ports:
      - '1880:1880'
    entrypoint: >
      sh -c "
      npm install --prefix /data --unsafe-perm --no-update-notifier --no-fund --only=production
      && npm --no-update-notifier --no-fund start --cache /data/.npm -- --userDir /data"
    environment:
      FLOWS: "nodered.json"
    volumes:
      - './nodered_data:/data'
    networks:
      coleta:
        ipv4_address: 10.50.50.3
    restart: always

  influxdb:
    image: 'influxdb:latest'
    pull_policy: always
    container_name: influxdb
    tty: true 
    stdin_open: true
    ports:
      - '8086:8086'
    environment:
      DOCKER_INFLUXDB_INIT_MODE: "setup"
      DOCKER_INFLUXDB_INIT_USERNAME: "admin"
      DOCKER_INFLUXDB_INIT_PASSWORD: "admin1234"
      DOCKER_INFLUXDB_INIT_ORG: "UFRGS"
      DOCKER_INFLUXDB_INIT_BUCKET: "database"
    volumes:
      - '/data/influx_data:/var/lib/influxdb2'
      - '/data/influx_data/config:/etc/influxdb2'
    networks:
      coleta:
        ipv4_address: 10.50.50.2
    restart: always

networks:
  coleta:
    driver: overlay
    ipam:
      config:
        - subnet: 10.50.50.0/24
  
