version: "3.9"

services:
  nodered:
    image: 'nodered/node-red:latest'
    pull_policy: always
    container_name: mynodered
    tty: true 
    stdin_open: true
    ports:
      - '1880:1880'
    entrypoint: >
      sh -c "
      npm install --prefix /data --unsafe-perm --no-update-notifier --no-fund --only=production
      && npm --no-update-notifier --no-fund start --cache /data/.npm -- --userDir /data"
    environment:
      FLOWS: "nodered.json"
    volumes:
      - './nodered_data:/data'
    restart: always

  influxdb:
    image: 'influxdb:latest'
    pull_policy: always
    container_name: influxdb
    tty: true 
    stdin_open: true
    ports:
      - '8086:8086'
    enviroment:
      
    volumes:
      - '/data/influx_data:/var/lib/influxdb'
    restart: always
  
